# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
cards = []
cards << Card.create(name: 'Magician', description: "The Magician is about making higher - and better - use of all of one's power. Spiritual, emotional, and otherwise. This is another card that often signifies new beginnings and great expectations. This is a very powerful, positive omen in a reading. This card reminds us that we have the power to make a difference, in our lives and in the greater world, if we simply make a point to try." , image: "cards/magician.jpg")
cards << Card.create(name: 'The High Priestess', description: "This is a time to rely on your intuition and your inner knowledge, rather than your conscious mind or intellect. Pay attention to your dreams. Synchronicities are likely now. When the High Priestess appears in a man's reading, she also often represents a woman that he will want badly; but whom he may not be able to get.", image: "/cards/high_priestess.jpg")
cards << Card.create(name: 'Empress', description: "People are going to be more attracted to you than usual (in every sense) and you are likely to find people on your doorstep, wanting your advice/your shoulder to cry on. This will be beneficial to you because you are now going to be able to see yourself more in the way that others see you - as someone with wisdom, and a lot to offer. So share your hard-won perspectives on life, know that your wisdom and caring is valuable.", image: "/cards/empress.jpg")
cards << Card.create(name: 'Emperor', description: "The Emperor shows us that domination of the mind over the heart is sometimes not wanted, but in some cases is it necessary and even welcomed, and that this is part of what we must think about when he appears. When hard choices must be made it's important to maintain your concentration and focus, and this is something this time period will make it easy for you to do. Enjoy the assertiveness and confidence it that this self-control and focus brings. Forge ahead and do what you know is best. If you can master yourself then you should have little problem mastering the world and all the things in it.", image: "cards/emperor.jpg")
cards << Card.create(name: 'Pope', description: "The Pope is very much about 'doing the right thing.' You may be struggling with an issue and are unsure about what is 'right' for you to do. Know that the answers are within you. Remember that the 'right' thing is what is right for you also.", image: "cards/pope.jpg")
cards << Card.create(name: 'Lovers', description: "It's possible when this card appears that you are feeling ambivalent about a relationship or situation in your life. It could be that your heart is telling you one thing, and your head, another. In general, the thing to do is (within the bounds of your morality) to follow your heart. Some people say there are only two modes that any of us are operating under at any time; and that's 'fear' or 'love'. When you can: choose love.", image: "cards/lovers.jpg")
cards << Card.create(name: 'Chariot', description: "The Chariot indicates a lot of energy but not free-for-all energy. It's directed, controlled, and has a goal in mind. When this card appears you are likely to be fairly clear on what your hopes and dreams involve and what you are willing to do to get there.", image: "cards/chariot.jpg")
cards << Card.create(name: 'Justice', description: "Justice deals with the idea of karma and the law of cause and effect, stating that all events, and all people, are connected. It's important to remember that not everything you are dealing with, however, is a direct result of your own actions or karma. Sometimes you will be called upon to deal with the results of the actions of someone you care about, and this can sometimes be as difficult and demanding as it is when you're up against something that is completely of your own making. Don't blame yourself unnecessarily.", image: "cards/justice.jpg")
cards << Card.create(name: 'Hermit', description: "Just like with the Strength card, you may even more so be in the frame of mind that you need some time alone - don't be afraid to take it. Even if it's just a five minute walk around the house so that you can clear your head. This is also very much a card about 'trying very hard to do the right thing.' Just make sure that 'doing the right thing' includes doing what is right for you personally, and not just worrying about the wants and needs of others.", image: "cards/hermit.jpg")
cards << Card.create(name: 'Wheel of Fortune', description: "The Wheel of Fortune tells you that in general, it looks as though things are changing. In most cases, this indicates positive, needed changes but for some people, change itself is very difficult and can almost be traumatic. This is a very spiritual and 'Karmically' oriented time. Change is part of the cyclical nature of life.", image: "cards/wheel_of_fortune.jpg")
cards << Card.create(name: 'Strength', description: "Strength indicates the importance of mind over matter, and reminds you to focus on what you do want rather than what you don't want in your life. Its main point is that you have the ability to harness your thoughts and to use them for your - and everyone else's - highest good. Not only do you have the ability; you have the responsibility. So conquer your fears, control your impulses, and never lose patience with yourself or what you are doing.", image: "cards/strength.jpg")

cards << Card.create(name: 'Hanged Man', description: "The Hanged Man generally shows that you are at a crossroads - one with only two options i.e. in or out, up or down, yes or no. You may find yourself very much wanting to do 'something' but having no idea what it is or how to do it. If that happens, that's a clear sign that you should stop, relax, and look at ways that you might need to let go of attempts to control life/situations/people/things.", image: "cards/hanged_man.jpg")
cards << Card.create(name: 'Death', description: "Death does not indicate physical death. This card simply indicates transformation and change. This is definitely a time of deep transformation, likely to be both inner and outwardly in your life. Situations, things, and people that you have counted on or gotten used to may no longer be available to you in quite the same way as they once were, and this transition can be difficult for some people.", image: "cards/death.jpg")
cards << Card.create(name: 'Temperance', description: "Temperance is a card about balance, in many ways, and relationships of all kinds. Friendships, family, romantic partnerships, and work partnerships all need your attention. This is also a card about alchemy or mixing and matching. You may have to try several approaches to things before you find what is truly right for you.", image: "cards/temperance.jpg")
cards << Card.create(name: 'Devil', description: "The Devil is not as frightening a card to interpret as the depiction on most cards indicates. It is a card about bondage but often this bondage is metaphoric and internal. With this card  you are called to look beyond superficial appearances and to go deeper into the truth and meaning of a situation. You also are asked to remember that  when you're feeling restrained you nearly always hold the keys to your own freedom. Don't give up hope!", image: "cards/devil.jpg")
cards << Card.create(name: 'Tower', description: "It is likely that some people/situations that you have counted on as being there for you may no longer be there in quite the same way. This doesn't have to be dire; change is the nature of life, and trying to prevent it is like trying to row upstream without a paddle. If  you have been building castles in the air this may be the time that some of them come crashing down to earth. That's only a problem if you let it be. You will be able to replace them with some more realistic and reachable dreams and goals if some fantasies fall apart this month. Dreaming is important, but it's also important to be living in reality too. You will get through this time just fine; particularly if you remember that you have all the resources you need, already inside you, to deal with life and to do what you need to do.", image: "cards/tower.jpg")
cards << Card.create(name: 'Star', description: "When the Star appears, you are likely to find yourself feeling rather inspired. You will be feeling more hopeful about the future, and more confident that your needs - whether these are emotional or financial needs or both - will be met. This is also a very spiritual card. You may find yourself for a time feeling at one with all of creation. Savor it.", image: "cards/star.jpg")
cards << Card.create(name: 'Moon', description: "The Moon indicates that things may seem somewhat confusing to you now. You may find it hard to understand where you are coming from, much less what others are thinking and feeling! You need to try to sit with the uncertainty, don't try to force things or people to do things before they are ready. This card is the 'Pisces' of the tarot deck.", image: "cards/moon.jpg")
cards << Card.create(name: 'Sun', description: "When the Sun card shows for you, it's a sign that soon you are likely to find yourself feeling more free than you have in a while - maybe years. This is a great time to take a vacation and to experience different things. The Sun is about vitality, freedom, joy, and self-expression.", image: "cards/sun.jpg")
cards << Card.create(name: 'Judgement', description: "Judgment can be a card about jumping to conclusions, decisions and judgments. which are too hastily made. If you are prone to such things, this is a clear signal to slow down and give things more thought and to give people 'more chances.' This can be a real time of spiritual awakening.", image: "cards/judgement.jpg")
cards << Card.create(name: 'World', description: "The World can signify that you are figuratively feeling the weight of the world on your shoulders, which is not an easy place to be. It's an excellent time to review how well you do at 'asking for help' when you need it. Remember you don't have to do everything on your own.", image: "cards/world.jpg")
cards << Card.create(name: 'Fool', description: "The Fool is always an indicator of newness; as well as the purity and open-hearted energy of a child. This is generally considered a positive card, with the caveat that it's important to take time to be sure that you are 'looking where you're going.'", image: "cards/fool.jpg")




cards << Card.create(name: 'Ace of Wands', description: "Aces of any suit usually indicate new beginnings - generally very positive ones. Wands are in the realm of accomplishment and are often generally related to work/career. If you are having a difficult time and draw the Ace of Wands in a reading, know that things are likely to be getting much better very soon!", image: "cards/ace_of_wands.jpg")
cards << Card.create(name: '2 of Wands', description: "In general the 2 of Wands reminds us to stay mindful of the give-and-take required for all successful relationships. If things are feeling 'out of balance' for you in general now, know that they are about to get substantially better. Keep your eyes on the prize that you're looking for, metaphorically, and remain or get positive.", image: "cards/two_of_wands.jpg")
cards << Card.create(name: '3 of Wands', description: "In general the 3 of Wands refers to work, in an extremely positive way. Even if you don't work outside the home, it means that your efforts are seen, appreciated, and are well respected. Give yourself some credit.", image: "cards/three_of_wands.jpg")
cards << Card.create(name: '4 of Wands', description: "The 4 of Wands often indicates that you may be attending a special event - one which will be way more fun than you are anticipating. So, go, and have a good time. Business is also likely to be going very well at this time, you will be proud of yourself, and others will be proud of you.", image: "cards/four_of_wands.jpg")
cards << Card.create(name: '5 of Wands', description: "The 5 of Wands often refers to competition. Usually this is in the career/work arena, but sometimes it can refer to romantic rivals. Don't be afraid of competing, know that you have something to offer, and can be successful. But you have to try, to see results. When this card appears, your need to believe in yourself is stronger than ever now. Hold your head up high, and have faith that you will end up in the place that is right for you. You may be thinking of making a career change. Know that you can be successful, if so.", image: "cards/five_of_wands.jpg")
cards << Card.create(name: '6 of Wands', description: "In general, the 6 is about happiness and celebration. You are about to see some results for your hard work and efforts. Give yourself a break or treat yourself in some way. You have certainly earned it.", image: "cards/six_of_wands.jpg")
cards << Card.create(name: '7 of Wands', description: "Don't hesitate to make where you stand clear to people. Your thinking is clear, and you are likely to help someone out by spelling things out for them. This card can indicate that a change is coming - a positive change - in your personal or business life. This card also points toward being independent and thinking for yourself.", image: "cards/seven_of_wands.jpg")
cards << Card.create(name: '8 of Wands', description: "A lot of things may be up in the air for you when the 8 of Wands appears. You may be frustrated, tired of waiting. This card is an indicator to be patient a while longer. You may have already done all you can do, and decisions now must be made by other people.", image: "cards/eight_of_wands.jpg")
cards << Card.create(name: '9 of Wands', description: "When the 9 of Wands comes up, the first and best step is often to take a deep breath and calm down. Don't let the things you are worried about overwhelm you. Take it one day at a time, one hour at a time, if you must. At least some of your worries will very likely turn out to be imaginary. Get very specific on what you are afraid of and pick it apart. What is the true likelihood of the worry actually happening? Comfort yourself, and if you need help, don't hesitate to ask for it. Asking for help is the mark of a strong person.", image: "cards/nine_of_wands.jpg")
cards << Card.create(name: '10 of Wands', description: "When the 10 of Wands appears, you may feel as though you are carrying a very heavy burden. You may want to look hard at this and see if there are any ways that you might lighten your load either literally or figuratively. If you look carefully you may find that part of the burden you are carrying emotionally actually belongs to someone else. It will be important for you to pace yourself now. Don't try to do too much.", image: "cards/ten_of_wands.jpg")
cards << Card.create(name: 'Page of Wands', description: "The face cards such as the Page very often indicate a literal person in our lives. In this case, it can indicate a female who is younger than the querent. Wands people are warm, ambitious, and usually high achievers. If not a literal person, the Page of Wands indicates the energy of easy distraction. Try to stay focused.", image: "cards/page_of_wands.jpg")
cards << Card.create(name: 'Knight of Wands', description: "When the Knight of Wands appears, this is a great time for travel if you can manage to get away. You should be feeling charged up, full of energy, and ready to get things done. Your self-confidence is likely to be increasing and this should help you toward your goals.", image: "cards/knight_of_wands.jpg")
cards << Card.create(name: 'Queen of Wands', description: "The Queen of Wands is one of the most fertile (metaphorically and literally) and feminine/womanly energies in the Tarot deck. In a reading, like all court cards, she can often signify a literal person in our lives, most often female, and most often with hair tending toward the lighter shades in the spectrum. The Queen brings good energy, and is a positive sign to receive.", image: "cards/queen_of_wands.jpg")
cards << Card.create(name: 'King of Wands', description: "Often associated with the astrological sign of Sagittarius, the King of Wands signifies wise, open, positive, adventurous masculine energy. As with all court cards, the King can indicate a literal person in your life; most often a man with hair on the lighter end of the spectrum. When the King appears, you are likely to have an abundance of energy which you are inclined to use in a positive direction.", image: "cards/king_of_wands.jpg")





