# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
cards = []
cards << Card.create(name: 'Magician', description: "The Magician is about making higher - and better - use of all of one's power. Spiritual, emotional, and otherwise. This is another card that often signifies new beginnings and great expectations. This is a very powerful, positive omen in a reading. This card reminds us that we have the power to make a difference, in our lives and in the greater world, if we simply make a point to try." , image: "cards/magician.jpg")
cards << Card.create(name: 'The High Priestess', description: "This is a time to rely on your intuition and your inner knowledge, rather than your conscious mind or intellect. Pay attention to your dreams. Synchronicities are likely now. When the High Priestess appears in a man's reading, she also often represents a woman that he will want badly; but whom he may not be able to get.", image: "/cards/high_priestess.jpg")
cards << Card.create(name: 'Empress', description: "People are going to be more attracted to you than usual (in every sense) and you are likely to find people on your doorstep, wanting your advice/your shoulder to cry on. This will be beneficial to you because you are now going to be able to see yourself more in the way that others see you - as someone with wisdom, and a lot to offer. So share your hard-won perspectives on life, know that your wisdom and caring is valuable.", image: "/cards/empress.jpg")
cards << Card.create(name: 'Emperor', description: "The Emperor shows us that domination of the mind over the heart is sometimes not wanted, but in some cases is it necessary and even welcomed, and that this is part of what we must think about when he appears. When hard choices must be made it's important to maintain your concentration and focus, and this is something this time period will make it easy for you to do. Enjoy the assertiveness and confidence it that this self-control and focus brings. Forge ahead and do what you know is best. If you can master yourself then you should have little problem mastering the world and all the things in it.", image: "cards/emperor.jpg")
cards << Card.create(name: 'Pope', description: "The Pope is very much about 'doing the right thing.' You may be struggling with an issue and are unsure about what is 'right' for you to do. Know that the answers are within you. Remember that the 'right' thing is what is right for you also.", image: "cards/pope.jpg")
cards << Card.create(name: 'Lovers', description: "It's possible when this card appears that you are feeling ambivalent about a relationship or situation in your life. It could be that your heart is telling you one thing, and your head, another. In general, the thing to do is (within the bounds of your morality) to follow your heart. Some people say there are only two modes that any of us are operating under at any time; and that's 'fear' or 'love'. When you can: choose love.", image: "cards/lovers.jpg")
cards << Card.create(name: 'Chariot', description: "The Chariot indicates a lot of energy but not free-for-all energy. It's directed, controlled, and has a goal in mind. When this card appears you are likely to be fairly clear on what your hopes and dreams involve and what you are willing to do to get there.", image: "cards/chariot.jpg")
cards << Card.create(name: 'Justice', description: "Justice deals with the idea of karma and the law of cause and effect, stating that all events, and all people, are connected. It's important to remember that not everything you are dealing with, however, is a direct result of your own actions or karma. Sometimes you will be called upon to deal with the results of the actions of someone you care about, and this can sometimes be as difficult and demanding as it is when you're up against something that is completely of your own making. Don't blame yourself unnecessarily.", image: "cards/justice.jpg")
cards << Card.create(name: 'Hermit', description: "Just like with the Strength card, you may even more so be in the frame of mind that you need some time alone - don't be afraid to take it. Even if it's just a five minute walk around the house so that you can clear your head. This is also very much a card about 'trying very hard to do the right thing.' Just make sure that 'doing the right thing' includes doing what is right for you personally, and not just worrying about the wants and needs of others.", image: "cards/hermit.jpg")
cards << Card.create(name: 'Wheel of Fortune', description: "The Wheel of Fortune tells you that in general, it looks as though things are changing. In most cases, this indicates positive, needed changes but for some people, change itself is very difficult and can almost be traumatic. This is a very spiritual and 'Karmically' oriented time. Change is part of the cyclical nature of life.", image: "cards/wheel_of_fortune.jpg")
cards << Card.create(name: 'Strength', description: "Strength indicates the importance of mind over matter, and reminds you to focus on what you do want rather than what you don't want in your life. Its main point is that you have the ability to harness your thoughts and to use them for your - and everyone else's - highest good. Not only do you have the ability; you have the responsibility. So conquer your fears, control your impulses, and never lose patience with yourself or what you are doing.", image: "cards/strength.jpg")

cards << Card.create(name: 'Hanged Man', description: "The Hanged Man generally shows that you are at a crossroads - one with only two options i.e. in or out, up or down, yes or no. You may find yourself very much wanting to do 'something' but having no idea what it is or how to do it. If that happens, that's a clear sign that you should stop, relax, and look at ways that you might need to let go of attempts to control life/situations/people/things.", image: "cards/hanged_man.jpg")
cards << Card.create(name: 'Death', description: "Death does not indicate physical death. This card simply indicates transformation and change. This is definitely a time of deep transformation, likely to be both inner and outwardly in your life. Situations, things, and people that you have counted on or gotten used to may no longer be available to you in quite the same way as they once were, and this transition can be difficult for some people.", image: "cards/death.jpg")
cards << Card.create(name: 'Temperance', description: "Temperance is a card about balance, in many ways, and relationships of all kinds. Friendships, family, romantic partnerships, and work partnerships all need your attention. This is also a card about alchemy or mixing and matching. You may have to try several approaches to things before you find what is truly right for you.", image: "cards/temperance.jpg")
cards << Card.create(name: 'Devil', description: "The Devil is not as frightening a card to interpret as the depiction on most cards indicates. It is a card about bondage but often this bondage is metaphoric and internal. With this card  you are called to look beyond superficial appearances and to go deeper into the truth and meaning of a situation. You also are asked to remember that  when you're feeling restrained you nearly always hold the keys to your own freedom. Don't give up hope!", image: "cards/devil.jpg")
cards << Card.create(name: 'Tower', description: "It is likely that some people/situations that you have counted on as being there for you may no longer be there in quite the same way. This doesn't have to be dire; change is the nature of life, and trying to prevent it is like trying to row upstream without a paddle. If  you have been building castles in the air this may be the time that some of them come crashing down to earth. That's only a problem if you let it be. You will be able to replace them with some more realistic and reachable dreams and goals if some fantasies fall apart this month. Dreaming is important, but it's also important to be living in reality too. You will get through this time just fine; particularly if you remember that you have all the resources you need, already inside you, to deal with life and to do what you need to do.", image: "cards/tower.jpg")
cards << Card.create(name: 'Star', description: "When the Star appears, you are likely to find yourself feeling rather inspired. You will be feeling more hopeful about the future, and more confident that your needs - whether these are emotional or financial needs or both - will be met. This is also a very spiritual card. You may find yourself for a time feeling at one with all of creation. Savor it.", image: "cards/star.jpg")
cards << Card.create(name: 'Moon', description: "The Moon indicates that things may seem somewhat confusing to you now. You may find it hard to understand where you are coming from, much less what others are thinking and feeling! You need to try to sit with the uncertainty, don't try to force things or people to do things before they are ready. This card is the 'Pisces' of the tarot deck.", image: "cards/moon.jpg")
cards << Card.create(name: 'Sun', description: "When the Sun card shows for you, it's a sign that soon you are likely to find yourself feeling more free than you have in a while - maybe years. This is a great time to take a vacation and to experience different things. The Sun is about vitality, freedom, joy, and self-expression.", image: "cards/sun.jpg")
cards << Card.create(name: 'Judgement', description: "Judgment can be a card about jumping to conclusions, decisions and judgments. which are too hastily made. If you are prone to such things, this is a clear signal to slow down and give things more thought and to give people 'more chances.' This can be a real time of spiritual awakening.", image: "cards/judgement.jpg")
cards << Card.create(name: 'World', description: "The World can signify that you are figuratively feeling the weight of the world on your shoulders, which is not an easy place to be. It's an excellent time to review how well you do at 'asking for help' when you need it. Remember you don't have to do everything on your own.", image: "cards/world.jpg")
cards << Card.create(name: 'Fool', description: "The Fool is always an indicator of newness; as well as the purity and open-hearted energy of a child. This is generally considered a positive card, with the caveat that it's important to take time to be sure that you are 'looking where you're going.'", image: "cards/fool.jpg")




cards << Card.create(name: 'Ace of Wands', description: "Aces of any suit usually indicate new beginnings - generally very positive ones. Wands are in the realm of accomplishment and are often generally related to work/career. If you are having a difficult time and draw the Ace of Wands in a reading, know that things are likely to be getting much better very soon!", image: "cards/ace_of_wands.jpg")
cards << Card.create(name: '2 of Wands', description: "In general the 2 of Wands reminds us to stay mindful of the give-and-take required for all successful relationships. If things are feeling 'out of balance' for you in general now, know that they are about to get substantially better. Keep your eyes on the prize that you're looking for, metaphorically, and remain or get positive.", image: "cards/two_of_wands.jpg")
cards << Card.create(name: '3 of Wands', description: "In general the 3 of Wands refers to work, in an extremely positive way. Even if you don't work outside the home, it means that your efforts are seen, appreciated, and are well respected. Give yourself some credit.", image: "cards/three_of_wands.jpg")
cards << Card.create(name: '4 of Wands', description: "The 4 of Wands often indicates that you may be attending a special event - one which will be way more fun than you are anticipating. So, go, and have a good time. Business is also likely to be going very well at this time, you will be proud of yourself, and others will be proud of you.", image: "cards/four_of_wands.jpg")
cards << Card.create(name: '5 of Wands', description: "The 5 of Wands often refers to competition. Usually this is in the career/work arena, but sometimes it can refer to romantic rivals. Don't be afraid of competing, know that you have something to offer, and can be successful. But you have to try, to see results. When this card appears, your need to believe in yourself is stronger than ever now. Hold your head up high, and have faith that you will end up in the place that is right for you. You may be thinking of making a career change. Know that you can be successful, if so.", image: "cards/five_of_wands.jpg")
cards << Card.create(name: '6 of Wands', description: "In general, the 6 is about happiness and celebration. You are about to see some results for your hard work and efforts. Give yourself a break or treat yourself in some way. You have certainly earned it.", image: "cards/six_of_wands.jpg")
cards << Card.create(name: '7 of Wands', description: "Don't hesitate to make where you stand clear to people. Your thinking is clear, and you are likely to help someone out by spelling things out for them. This card can indicate that a change is coming - a positive change - in your personal or business life. This card also points toward being independent and thinking for yourself.", image: "cards/seven_of_wands.jpg")
cards << Card.create(name: '8 of Wands', description: "A lot of things may be up in the air for you when the 8 of Wands appears. You may be frustrated, tired of waiting. This card is an indicator to be patient a while longer. You may have already done all you can do, and decisions now must be made by other people.", image: "cards/eight_of_wands.jpg")
cards << Card.create(name: '9 of Wands', description: "When the 9 of Wands comes up, the first and best step is often to take a deep breath and calm down. Don't let the things you are worried about overwhelm you. Take it one day at a time, one hour at a time, if you must. At least some of your worries will very likely turn out to be imaginary. Get very specific on what you are afraid of and pick it apart. What is the true likelihood of the worry actually happening? Comfort yourself, and if you need help, don't hesitate to ask for it. Asking for help is the mark of a strong person.", image: "cards/nine_of_wands.jpg")
cards << Card.create(name: '10 of Wands', description: "When the 10 of Wands appears, you may feel as though you are carrying a very heavy burden. You may want to look hard at this and see if there are any ways that you might lighten your load either literally or figuratively. If you look carefully you may find that part of the burden you are carrying emotionally actually belongs to someone else. It will be important for you to pace yourself now. Don't try to do too much.", image: "cards/ten_of_wands.jpg")
cards << Card.create(name: 'Page of Wands', description: "The face cards such as the Page very often indicate a literal person in our lives. In this case, it can indicate a female who is younger than the querent. Wands people are warm, ambitious, and usually high achievers. If not a literal person, the Page of Wands indicates the energy of easy distraction. Try to stay focused.", image: "cards/page_of_wands.jpg")
cards << Card.create(name: 'Knight of Wands', description: "When the Knight of Wands appears, this is a great time for travel if you can manage to get away. You should be feeling charged up, full of energy, and ready to get things done. Your self-confidence is likely to be increasing and this should help you toward your goals.", image: "cards/knight_of_wands.jpg")
cards << Card.create(name: 'Queen of Wands', description: "The Queen of Wands is one of the most fertile (metaphorically and literally) and feminine/womanly energies in the Tarot deck. In a reading, like all court cards, she can often signify a literal person in our lives, most often female, and most often with hair tending toward the lighter shades in the spectrum. The Queen brings good energy, and is a positive sign to receive.", image: "cards/queen_of_wands.jpg")
cards << Card.create(name: 'King of Wands', description: "Often associated with the astrological sign of Sagittarius, the King of Wands signifies wise, open, positive, adventurous masculine energy. As with all court cards, the King can indicate a literal person in your life; most often a man with hair on the lighter end of the spectrum. When the King appears, you are likely to have an abundance of energy which you are inclined to use in a positive direction.", image: "cards/king_of_wands.jpg")


cards << Card.create(name: 'Ace of Cups', description: "Things are looking up! In general, people will respond to you with happiness, love, and goodwill, more than usually in the near future. You should be feeling good. This is a great time to make friends. This can also signify a promotion and/or new, good job headed your way. You and your work are appreciated and valued - and you should see signs of this soon.", image: "cards/ace_of_cups.jpg")
cards << Card.create(name: '2 of Cups', description: "The 2 of Cups often refers to romantic partnership, but that is not its only connotation. It can speak of balance, friendship, joy, and sharing. In general this is a card that says that things are likely to be going well. You should be feeling more than usually loved, cared for, and content.", image: "cards/two_of_cups.jpg")
cards << Card.create(name: '3 of Cups', description: "The 3 of Cups is often considered to be a card of 'reunions.' But this is not always a romantic reunion, alas… it's reunion in the broadest sense, running back into (or meeting with, purposefully) someone or something that you have been away from for some time. It's generally considered to be a happy reunion, an upbeat card.", image: "cards/three_of_cups.jpg")
cards << Card.create(name: '4 of Cups', description: "The 4 of Cups is a card about wishful thinking. It warns us to remember to pay attention to what 'is' now, and the many blessings we each currently experience, and not to worry too much about 'what could be.'", image: "cards/four_of_cups.jpg")
cards << Card.create(name: '5 of Cups', description: "In most tarot decks, most depictions on each card give solid guides toward interpretation, for this card, this is more than usually the case. Most often, a sad or downcast figure is shown, with five cups. Three are spilled, and two remain upright and whole. The implication is extremely clear; are you going to cry over 'spilt milk' or are you going to focus on the 'milk' you still have, and get on with things? The point is: watch where you put your focus and make sure that the focus is for your highest good.", image: "cards/five_of_cups.jpg")
cards << Card.create(name: '6 of Cups', description: "It's important not to spend too much time and effort thinking about the 'good old days.' We all have happy memories to reflect on from time to time, but if we start thinking that the 'best of all years have gone by', then that can become a self fulfilling prophecy.", image: "cards/six_of_cups.jpg")
cards << Card.create(name: '7 of Cups', description: "In general this card points to a need to narrow your focus. When it appears, you are probably trying to do too much, and doing most of it not very well. Choose just a few of the myriad things that are on your plate, and work through these items one by one, carefully. You may be feeling overwhelmed. Remember that you can control at least in some areas, how much you are trying to take on.", image: "cards/seven_of_cups.jpg")
cards << Card.create(name: '8 of Cups', description: "Know that renewed good times lie ahead for you. If your 'gut' is telling you that you really need to get out of a relationship, job, or living arrangement, trust yourself. Instead of this coming out of the blue, or someone or something leaving you, it usually means that you are the one who will make this choice. Very often one door has to close behind you before the next door in front of you can fully open.", image: "cards/eight_of_cups.jpg")
cards << Card.create(name: '9 of Cups', description: "The appearance of this card is usually a portent of happiness, and good things about to come. It also usually means that what you want is likely to come into being in your life. If asking a yes/no type of question, this card is the most powerful indicator of 'yes', but like everything else in the tarot, that is not carved in stone.", image: "cards/nine_of_cups.jpg")
cards << Card.create(name: '10 of Cups', description: "The 10 of Cups is another of the most uplifting of cards that you can receive. This card points to happiness in general, perhaps in a more mature, grown-up, global kind of way as opposed to the more personal, less global, wish fulfillment promised by the 9 of Cups. Either way it's a good card.", image: "cards/ten_of_cups.jpg")
cards << Card.create(name: 'Page of Cups', description: "When the Page of Cups appears, it's a signal to allow the childlike side of yourself to come forward. Like most of the Cups suit, the Page is an uplifting and encouraging sign to receive in a tarot reading. It also can indicate that someone - likely someone who is younger than you, is coming your way before long with a message for you.", image: "cards/page_of_cups.jpg")
cards << Card.create(name: 'Knight of Cups', description: "The Knight of Cups like most if not all of the Cups suit, is an optimistic, good card to see in a reading. Like all Knights/Knights, this one often comes bearing messages. Usually these are the kind of good news that we all want to receive.", image: "cards/knight_of_cups.jpg")
cards << Card.create(name: 'Queen of Cups', description: "The Queen of Cups is among the most loving archetypes in the tarot deck. She indicates compassion, love, and concern for ourselves and our fellow man. Often when the 'court cards' come up in a reading, they indicate an actual person, in this case a woman, in our lives. The majority of the time when the queen of Cups appears, and is 'standing in' for a person, she is representing a female with hair on the lighter end of the spectrum.", image: "cards/queen_of_cups.jpg")
cards << Card.create(name: 'King of Cups', description: "The King of Cups speaks of balanced male and feminine energy; he holds all the positive qualities of both masculine and feminine. Often he indicates a literal man in your life. Usually, when he represents a ‘live person', he's referring to a very kind and loving man, who will generally have hair on the lighter end of the spectrum. Know that you are supported by the universe, in ways seen and unseen, when he appears.", image: "cards/king_of_cups.jpg")



cards << Card.create(name: 'Ace of Swords', description: "As with all Aces, The Ace of Swords can indicate a new beginning of some sort in your life, possibly on several fronts. Sometimes this new beginning can be started by a separation of some kind - from a relationship, or from a job situation. Know that as anxiety-producing as such a new beginning can sometimes be, that underneath it all is good, beneficial energy that is getting you where you want to go.", image: "cards/ace_of_swords.jpg")
cards << Card.create(name: '2 of Swords', description: "In general the 2 of Swords tells us that your partnerships are likely to be going at least somewhat well, whether these be friendships, romantic, or business. However, you should consider the depths of your commitment to equality in these and whether or not you are being treated as an equal by your partners. If you are not, it may be time to bring things back into balance. This will almost certainly require open communication on your part. Nothing changes without effort.", image: "cards/two_of_swords.jpg")
cards << Card.create(name: '3 of Swords', description: "Regardless of the way that the 3 of Swords card is depicted in most Tarot decks (a heart with Swords going through it,) know that it is not all bad. Although there is an element of sorrow that is undeniable when this card appears, what lies on the other side of this sorrow can be enhanced understanding and joy. Allow yourself to fully experience any sorrow or pain that comes up now, so that you can move beyond it.", image: "cards/three_of_swords.jpg")
cards << Card.create(name: '4 of Swords', description: "In general this card usually means that you are needing some time and space to yourself. Others may be pushing too hard for bits of your time and attention. Don't hesitate to draw boundaries for yourself or to say no. Conversely, when others say no to you, take them at their word. Pushing in this circumstance is asking for trouble.", image: "cards/four_of_swords.jpg")
cards << Card.create(name: '5 of Swords', description: "When the 5 of Swords appears, you are likely to find yourself with some mixed feelings about life in general and about a few people in particular. Don't ignore these, but don't feel like you have to speak every word you're thinking and feeling either, as you could ruin the very things that you want the most - such as close, intimate relationships with your friends and lover. Think several times before you really let someone have it even if they deserve it. Pick your battles.", image: "cards/five_of_swords.jpg")
cards << Card.create(name: '6 of Swords', description: "When the 6 of Swords appears, this is a great time for travel of any sort. It also can indicate metaphorical movement, a change in where you are inwardly. Usually this is a change for the better, whether the context is internal or external. Think about where you want to be.", image: "cards/six_of_swords.jpg")
cards << Card.create(name: '7 of Swords', description: "The 7 of Swords can point to someone who is behaving with less than ethical intentions. It sometimes also means prying into someone's life where you don't belong. If you sense that someone is spying on you, you may be right. If you are tempted to dig through someone else's life (unless it is that of your minor child who has given you cause for concern), resist the impulse. Everyone deserves privacy.", image: "cards/seven_of_swords.jpg")
cards << Card.create(name: '8 of Swords', description: "In general, the 8 tells us that we must be open to defeat in order to ever possibly win. Do not fear the unknown; many blessings reside for you there. Examine your thoughts, speech, and behavior for negativity and know that what you say and do and the choices that you make affect the outcomes in your life. If you need help managing and dealing with your fears, ask for it.", image: "cards/eight_of_swords.jpg")
cards << Card.create(name: '9 of Swords', description: "You will need to guard against a feeling of anxiety. If you are feeling anxious, take a good look at whether or not any of that is under your own power or control (and thus, you could lessen it) or if other things or people in your life are contributing to this anxiety. If it is the latter, take a good look at that, and see whether or not something in the relationship can be changed to make it more workable for you. There's something about this time period that can cause people to feel like their life should be, in some way, 'more' or 'bigger' than it is. Try to take comfort and joy in the ordinary things. That's where the beauty is.", image: "cards/nine_of_swords.jpg")
cards << Card.create(name: '10 of Swords', description: "In general, when the 10 comes up in relation to a question as to whether you can believe what a person is telling you, or trust that a situation is stable, this is a pretty clear answer of 'no'. However, try to bear in mind that whenever a door closes, another door opens. You are being guided to a situation that is better for you. Trust yourself and trust in the universe.", image: "cards/ten_of_swords.jpg")
cards << Card.create(name: 'Page of Swords', description: "In general the Page of Swords tells us that the querent may be trying too hard, pushing too fast, or in general stepping on the toes of others. You may need to study the body language of others, and consider how well you do (or do not) accept constructive criticism from others. You are likely to have a great deal of mental and physical energy now. Use it wisely.", image: "cards/page_of_swords.jpg")
cards << Card.create(name: 'Knight of Swords', description: "Unlike a number of the Swords cards, the Knight of Swords actually brings a fairly upbeat and cheerful energy. Knights can often mean that someone or something desirable is about to seek you out. The Knight of Swords also points to your physical, emotional, and spiritual energy being at a peak.", image: "cards/knight_of_swords.jpg")
cards << Card.create(name: 'Queen of Swords', description: "In general the Queen of Swords can indicate that your instincts are serving you well. You already know what it is you want and need, now you just have to go after it. Be mindful of other people's boundaries as you are doing so, however. This Queen has forceful energy which some people find abrasive.", image: "cards/queen_of_swords.jpg")
cards << Card.create(name: 'King of Swords', description: "In general, the King of Swords points to very forceful energy. You may need to change something major about your behavior, thoughts, and/or expectations. Don't overextend your reach. The King of Swords might also stand in for a powerful, opinionated, forceful man in the querent's life. He will often, but not always, have hair on the darker end of the spectrum.", image: "cards/king_of_swords.jpg")
